config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # devise_scope :user do
  #   authenticated :user do
  #     root 'posts#index', as: :authenticated_root
  #   end
  #
  #   unauthenticated do
  #     root 'devise/sessions#new', as: :unauthenticated_root
  #   end
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :posts do
    resources :comments
    resources :upvotes, only: :create
    resources :downvotes, only: :create
  end
  resources :users, only: [:show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :text, :user_id, :post_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	self.per_page = 2
  belongs_to :user
  has_many :comments, dependent: :destroy
  mount_uploader :photo, PhotoUploader
  validates :photo, :description, :user_id, presence: true
  acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         mount_uploader :photo, PhotoUploader
         has_many :posts, dependent: :destroy
         has_many :comments, dependent: :destroy

         acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email,:password,:password_confirmation,:name,:photo)}
    devise_parameter_sanitizer.permit(:sign_in) {|u| u.permit(:email,:password,:remember_me)}
    devise_parameter_sanitizer.permit(:account_update){|u| u.permit(:current_password,:email,:password,:password_confirmation,:name,:photo)}
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: :create
  before_action :is_owner?, only: :destroy
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params.merge(user_id: current_user.id))
    if @comment.valid?
      redirect_to root_path
    else
      flash[:alert] = "Invalid attributes."
      redirect_to root_path
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :post_id)
  end
  def is_owner?
  @comment = Comment.find(params[:id])
  if @comment.user != current_user
    redirect_to root_path
  end
end
end

app/controllers/downvotes_controller.rb
class DownvotesController < ApplicationController
  before_action :authenticate_user!
  def create
    @post = Post.find(params[:post_id])
    @post.downvote_from current_user
    redirect_to posts_path
    respond_to do |format|
      format.html {}
      format.js {}
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :is_owner?, only: [:edit,:update,:destroy]
  def create
    @post = current_user.posts.create(post_params)
    if @post.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end
  def edit
    @post=Post.find(params[:id])
  end
  def index
    @posts = Post.paginate(page: params[:page], per_page: 2).order('created_at DESC')
    respond_to do |format|
    format.html
    format.js
    end
  end
  def new
    @post=Post.new
  end
  def update
    @post=Post.find(params[:id])
    if @post.update(post_params)
      redirect_to root_path
    else
      redirect_to edit_post_path(params[:id])
    end
  end
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end
  def show
    @post=Post.find(params[:id])
  end

  def upvote
  end

  def downvote
  end
  private

  def is_owner?
    redirect_to root_path if Post.find(params[:id]).user!=current_user
    end
  end
  def post_params
    params.require(:post).permit(:user_id,:photo,:description)
  end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
    before_action :authenticate_user!
  def create
    @post = Post.find(params[:post_id])
    @post.liked_by current_user
    redirect_to posts_path
    respond_to do |format|
      format.html {}
      format.js {}
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user=User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/downvotes_helper.rb
module DownvotesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/upvotes_helper.rb
module UpvotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/downvotes/create.js.erb
$('#likes_container_<%= @post.id %>').html("<%= escape_javascript render partial: '/posts/likes', locals: { post: @post } %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Share Your Photos Online - Instapost</title>
    <%= favicon_link_tag 'favicon.ico' %>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
  </head>

  <body>

    <nav>
        <div class="row" style="padding: 0px 50px;">
          <div class="nav_wrapper">
                <div class="col-md-4">
                    <span class="pull-left brand">
                      <i class="fa fa-instagram" aria-hidden="true"></i>  | <%= link_to 'Instapost', root_path %></span>
                </div>
                <div class="col-md-4">
                </div>
              <div class="col-md-4 navbar">
                  <div align="right">
                      <% if user_signed_in? %>
                        <span class="nav_links pull-right"><%= link_to 'New Post', new_post_path %></span>
                        <span class="nav_links pull-right"><%= link_to 'Edit Settings', edit_user_registration_path %></span>
                        <span class="nav_links pull-right"><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></span>
                      <% else %>
                      <% if controller_name!="sessions" %>
                        <span class="nav_links pull-right"><%= link_to 'Sign Up', new_user_registration_path %></span>
                        <span class="nav_links pull-right"><%= link_to 'Log In', new_user_session_path %></span>

                      <% end %>
                      <% end %>
                  </div>
              </div>
          </div>
        </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/_likes.html.erb
<% if user_signed_in? %>
  <span class="post_like">
    <% if current_user.voted_up_on? post %>
      <%= link_to '<i class="fa fa-heart" aria-hidden="true"></i>'.html_safe, post_downvotes_path(post.id), method: :post, remote: true %>
    <% else %>
      <%= link_to '<i class="fa fa-heart-o" aria-hidden="true"></i>'.html_safe, post_upvotes_path(post.id), method: :post, remote: true  %>
    <% end %>

    <%= pluralize post.get_likes.size, "like" %>
  </span>
<% else %>
  <span class="post_like">
    <i class="fa fa-heart-o" aria-hidden="true"></i> <%= pluralize post.get_likes.size, "like" %>
  </span>
<% end %>

app/views/posts/_post.html.erb
    <div class="post_box">
    <div class="post_header">
      <%= cl_image_tag post.user.photo, class: 'prof_pic_small' %>
      <%= link_to post.user.name, user_path(post.user_id) %>
      <span class="timestamp pull-right"><%= distance_of_time_in_words(DateTime.now, post.created_at) %> ago</span>
    </div>
      <%= cl_image_tag post.photo, class: 'photo' %><br/>
      <span id="likes_container_<%= post.id %>">
      <%= render partial: 'likes', locals: {post: post} %>
      </span><br/>
          <div class="post_body">

      <%= link_to post.user.name, user_path(post.user_id) %> <%= post.description %>

    </div> 
      
    <div class="post_comments">

      <% post.comments.each do |comment| %>

        <%= link_to comment.user.name,  user_path(comment.user_id) %> <%= comment.text %>

      <% end %>


      <hr>

      <% if user_signed_in? %>
        <%= simple_form_for Comment.new, url: post_comments_path(post), method: :post,  html: { class: 'form-horizontal' } do |f| %>
          <%= f.input :text, label: 'Comment', placeholder: 'Add a comment...' %>
          <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
        <% end %>
      <% end %>
    </div>
    </div>

app/views/posts/edit.html.erb
<h5>Edit Post</h5>
<%= simple_form_for @post do |f| %>
  <%= f.input :photo %>
  <%= f.input :description %>
  <%= f.submit 'Update', class: 'btn btn-default btn-block' %>
<% end %>

app/views/posts/index.html.erb
<div>
  <div class="col-md-3"></div>
  <div class="col-md-6">

<div id="my-posts">
  <%= render @posts %>
</div>

<div id="infinite-scrolling">
  <%= will_paginate @posts %>
</div>
</div>
<div class="col-md-3"></div>

app/views/posts/new.html.erb
<div>
  <div class="col-md-3">
  </div>
  <div class="col-md-6">
<div class="post_box" style="padding:30px">
<h2 align="center">Create new post</h2>
  <%= simple_form_for @post do |f| %>
    <%= f.input :photo %>
    <%= f.input :description %>
    <%= f.submit "Post", class: 'btn btn-default btn-block'%>
  <% end %>
  </div>
</div>
  <div class="cols-md-3"></div>
</div>

app/views/posts/show.html.erb
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="post_box">
    <div class="post_header">
      <%= cl_image_tag @post.user.photo, class: 'prof_pic_small' %>
      <%= link_to @post.user.name, user_path(@post.user_id) %>
      <span class="timestamp pull-right"><%= distance_of_time_in_words(DateTime.now, @post.created_at) %> ago</span>
    </div>
      <%= cl_image_tag @post.photo, class: 'photo' %><br/>
      <span id="likes_container_<%= @post.id %>">
      <%= render partial: 'likes', locals: {post: @post} %>
      </span><br/>
      <%= @post.description %><br/>
      <% if @post.user == current_user %>
        <%= link_to 'Edit Post', edit_post_path(@post.id) %>
        <%= link_to 'Delete Post', post_path(@post.id), method: :delete %>
      <% end %>
    <div class="post_body">

      <%= link_to @post.user.name, user_path(@post.user_id) %> <%= @post.description %>

    </div>

    <div class="post_comments">

      <% @post.comments.each do |comment| %>

        <%= link_to comment.user.name,  user_path(comment.user_id) %> <%= comment.text %>

      <% end %>


      <hr>

      <% if user_signed_in? %>
        <%= simple_form_for Comment.new, url: post_comments_path(@post), method: :post,  html: { class: 'form-horizontal' } do |f| %>
          <%= f.input :text, label: 'Comment', placeholder: 'Add a comment...' %>
          <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
        <% end %>
      <% end %>
    </div>
    </div>
  </div>
  <div class="col-md-3"></div>

app/views/upvotes/create.js.erb
$('#likes_container_<%= @post.id %>').html("<%= escape_javascript render partial: '/posts/likes', locals: { post: @post } %>")

app/views/users/show.html.erb
<div>
  <div class="col-md-3"></div>
  <div class="col-md-6">
<div class="post_box">
  <div class="prof_header">

  <div class="row">

    <div class="col-xs-4">
      <%= cl_image_tag @user.photo, class: 'prof_pic' %>
    </div>

    <div class="col-xs-8">

      <div class="user_header">

        <div class="row">
          <div class="col-xs-6">
            <h1 class = "username"><%= @user.name %></h1>
          </div>

          <div class="col-xs-6">
            <%= link_to 'EDIT PROFILE', edit_user_registration_path(@user), class: 'user_edit_button btn btn-default' if user_signed_in? && @user == current_user %>
          </div>
        </div>
      </div>

      <span class="count"><%= pluralize(@user.posts.count, 'post') %></span>

    </div>

  </div>

</div>

<hr>

<div class="prof_post_box">

  <div class="row">

    <% @user.posts.each do |post| %>

        <div class="col-xs-6">
          <%= cl_image_tag post.photo, class: 'prof_show' %>
        </div>

    <% end %>

  </div>
</div>
</div>
</div>
<div class="col-md-3"></div>
</div>